-- ============================================================
-- SCRIPT: historical_inventory_full_pipeline.sql
-- PURPOSE: Complete historical inventory pipeline with cost columns + ITEM_CUBE
-- DATE: May 25, 2026 (Updated Jun 2026 - Added ITEM_CUBE + daily mid-week refresh)
-- ============================================================


-- ============================================================
-- STEP 0: ITEM_CUR (TEMP TABLE)
-- ============================================================
CREATE OR REPLACE TEMP TABLE ITEM_CUR
CLUSTER BY MDS_FAM_ID
AS (
  SELECT *
  FROM (
    SELECT DISTINCT
      MDS_FAM_ID,
      ITEM_NBR,
      ITEM_REPLENISHABLE_IND,
      ACCTG_DEPT_NBR AS DEPT_NBR,
      WHPK_QTY,
      REPL_GROUP_NBR,
      CASE
        WHEN FINELINE_NBR = 8023 AND DEPT_NBR = 42 THEN 1
        WHEN ACCTG_DEPT_NBR = 19  AND DEPT_CATEGORY_NBR = 3072 THEN 1
        WHEN ACCTG_DEPT_NBR = 91  AND DEPT_CATEGORY_NBR = 3201 THEN 1
        WHEN ACCTG_DEPT_NBR = 95  AND FINELINE_NBR IN (9225,9226,9998,2353) THEN 1
        WHEN ACCTG_DEPT_NBR = 40  AND DEPT_CATEGORY_NBR IN (1808,1809,1788) THEN 1
        WHEN ACCTG_DEPT_NBR = 8   AND DEPT_CATEGORY_NBR IN (676) THEN 1
        WHEN ACCTG_DEPT_NBR = 2   AND DEPT_CATEGORY_NBR IN (546,542) THEN 1
        WHEN ACCTG_DEPT_NBR = 95  AND VENDOR_NAME = 'MCLANE COMPANY' THEN 1
        WHEN ITEM1_DESC IN (
          'PRICE ADJ','BR 15LB EXCHANGE','AMERIG PROPANE EXCH','0','1','4','42','72',
          '123','1408','1800','1843','1865','1917','1984','2067','71239','436166','453092',
          '9509766','133538321','36881149149','36881431565','36881455820','70616024240',
          '72286839404','323900040953','719410785109','861368000220',
          '*** DISCONTINUED***','***DISCONTINUED BY C','***DISCONTINUED BY V','***DISCONTINUED***',
          '***DISCONTINUED*** B','***DISCONTINUED*** L','***DISCONTINUED***BD',
          '***DISCONTINUED***CO','***DISCONTINUED***GL','***DISCONTINUED***HA',
          '***DISCONTINUED***LA','***DISCONTINUED***LY','***DISCONTINUED***MA',
          '***DISCONTINUED***MR','***DISCONTINUED***RU','***DISCONTINUED***TO',
          '**DISCONTINUED BY VE','**DISCONTINUED**','**DISCONTINUED** ARR',
          'DIESEL','REG GAS UNLEADED','REUSABLE BAGS','REUSABLE BAGS ASST 2',
          'FUEL PREPAY','HI-GRADE PREMIUM GAS','UNLEADED CLEAR','CAROUSEL REUSABLE BG'
        ) THEN 1
        ELSE 0
      END AS ITEM_EXCEPTIONS
    FROM `wmt-edw-prod.US_WM_VM.ITEM_CUR`
    WHERE ACCTG_DEPT_NBR NOT IN (99,39,37,38,49,85,60,83,86,88)
      AND MDSE_SEGMENT_DESC NOT IN ('HEALTH AND WELLNESS','WALMART SERVICES')
      AND VENDOR_NBR <> 481890
      AND REPL_SUBTYPE_CODE <> 99
      AND REPL_SUBTYPE_CODE NOT IN (16,89)
      AND REPL_SUBTYPE_CODE <> 21
      AND REPL_SUBTYPE_CODE <> 6
      AND DEPT_CATEGORY_NBR IS NOT NULL
      AND CONCAT(ACCTG_DEPT_NBR, DEPT_CATEGORY_NBR) NOT IN ('821425','821435','872873')
      AND CONCAT(ACCTG_DEPT_NBR, DEPT_CATG_GRP_NBR) NOT IN ('826379')
      AND CONCAT(ACCTG_DEPT_NBR, REPL_SUBTYPE_CODE) NOT IN ('8021','8014','9821')
      AND (VENDOR_SEQ_NBR + 10 * VENDOR_DEPT_NBR + 1000 * VENDOR_NBR) NOT IN (
          SELECT (VENDOR_SEQ_NBR + 10 * DEPT_NBR + 1000 * VENDOR_NBR)
          FROM `wmt-edw-prod.US_WM_VM.PFS_VENDOR_STORE`
          WHERE PFS_PRODUCTION_IND = 'P'
          GROUP BY VENDOR_NBR, DEPT_NBR, VENDOR_SEQ_NBR
      )
  )
  WHERE ITEM_EXCEPTIONS <> 1
);


-- ============================================================
-- STEP 1: STORE + FC CONSOLIDATED INVENTORY (with COST + ITEM_CUBE)
-- ============================================================
DROP TABLE IF EXISTS `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_STORE_FC_INVT`;

CREATE OR REPLACE TABLE `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_STORE_FC_INVT`
PARTITION BY BUS_DT
CLUSTER BY OMNI_CATG_NBR
AS (
  WITH store_channel AS (
    SELECT
      INVT.BUS_DT,
      INVT.MDS_FAM_ID,
      SUM(COALESCE(INVT.TY_ON_HAND_QTY, 0))       AS STORE_OH_UNITS,
      SUM(COALESCE(INVT.TY_ON_HAND_COST_AMT, 0))   AS STORE_OH_COST,
      SUM(COALESCE(INVT.TY_IN_WHSE_QTY, 0))        AS DC_RESERVED_UNITS,
      SUM(COALESCE(INVT.TY_IN_WHSE_COST_AMT, 0))   AS DC_RESERVED_COST,
      SUM(COALESCE(INVT.TY_IN_TRNST_QTY, 0))       AS IN_TRANSIT_UNITS,
      SUM(COALESCE(INVT.TY_IN_TRNST_COST_AMT, 0))  AS IN_TRANSIT_COST,
      INVT.OMNI_CATG_NBR,
      INVT.OMNI_CATG_DESC,
      INVT.OMNI_DEPT_NBR,
      INVT.OMNI_DEPT_DESC
    FROM `wmt-gdap-dl-sec-merch-bq-prod.us_fd_app_secure.fd_omni_chnl_item_dly` INVT
    WHERE INVT.BUS_DT >= '2025-02-07'
      AND (
        EXTRACT(DAYOFWEEK FROM INVT.BUS_DT) = 6
        OR (INVT.BUS_DT = DATE_SUB(CURRENT_DATE('America/Chicago'), INTERVAL 1 DAY)
            AND EXTRACT(DAYOFWEEK FROM CURRENT_DATE('America/Chicago')) BETWEEN 2 AND 6)
      )
      AND INVT.BUS_DT < CURRENT_DATE('America/Chicago')
      AND INVT.FULFMT_CHNL_NM = 'Store'
      AND INVT.OMNI_SEG_DESC NOT IN ('HEALTH AND WELLNESS','OTHER','WALMART SERVICES')
    GROUP BY
      INVT.BUS_DT, INVT.MDS_FAM_ID,
      INVT.OMNI_CATG_NBR, INVT.OMNI_CATG_DESC,
      INVT.OMNI_DEPT_NBR, INVT.OMNI_DEPT_DESC
  ),

  fc_channel AS (
    SELECT
      INVT.BUS_DT,
      INVT.MDS_FAM_ID,
      SUM(COALESCE(INVT.TY_FC_ON_HAND_UNIT_QTY, 0)) AS FC_OH_UNITS,
      SUM(COALESCE(INVT.TY_FC_ON_HAND_COST_AMT, 0))  AS FC_OH_COST,
      INVT.OMNI_CATG_NBR,
      INVT.OMNI_CATG_DESC,
      INVT.OMNI_DEPT_NBR,
      INVT.OMNI_DEPT_DESC
    FROM `wmt-gdap-dl-sec-merch-bq-prod.us_fd_app_secure.fd_omni_chnl_item_dly` INVT
    WHERE INVT.BUS_DT >= '2025-02-07'
      AND (
        EXTRACT(DAYOFWEEK FROM INVT.BUS_DT) = 6
        OR (INVT.BUS_DT = DATE_SUB(CURRENT_DATE('America/Chicago'), INTERVAL 1 DAY)
            AND EXTRACT(DAYOFWEEK FROM CURRENT_DATE('America/Chicago')) BETWEEN 2 AND 6)
      )
      AND INVT.BUS_DT < CURRENT_DATE('America/Chicago')
      AND INVT.FULFMT_CHNL_NM = 'OWNED'
      AND INVT.TY_FC_ON_HAND_UNIT_QTY > 0
      AND INVT.OMNI_SEG_DESC NOT IN ('HEALTH AND WELLNESS','OTHER','WALMART SERVICES')
    GROUP BY
      INVT.BUS_DT, INVT.MDS_FAM_ID,
      INVT.OMNI_CATG_NBR, INVT.OMNI_CATG_DESC,
      INVT.OMNI_DEPT_NBR, INVT.OMNI_DEPT_DESC
  )

  SELECT
    COALESCE(S.BUS_DT, F.BUS_DT)             AS BUS_DT,
    CAL.WM_FULL_YR_NBR                        AS WM_YEAR,
    CAL.WM_WK_NBR                             AS WM_WEEK,
    CAL.WM_YR_WK_NBR,
    COALESCE(S.MDS_FAM_ID, F.MDS_FAM_ID)     AS MDS_FAM_ID,
    SAFE_DIVIDE(OMNI.PKG_HT_IN_QTY * OMNI.PKG_WDTH_IN_QTY * OMNI.PKG_LEN_IN_QTY, 1728) AS ITEM_CUBE,
    COALESCE(S.STORE_OH_UNITS, 0)             AS STORE_OH_UNITS,
    COALESCE(S.STORE_OH_COST, 0)              AS STORE_OH_COST,
    COALESCE(S.DC_RESERVED_UNITS, 0)          AS DC_RESERVED_UNITS,
    COALESCE(S.DC_RESERVED_COST, 0)           AS DC_RESERVED_COST,
    COALESCE(S.IN_TRANSIT_UNITS, 0)           AS IN_TRANSIT_UNITS,
    COALESCE(S.IN_TRANSIT_COST, 0)            AS IN_TRANSIT_COST,
    COALESCE(F.FC_OH_UNITS, 0)                AS FC_OH_UNITS,
    COALESCE(F.FC_OH_COST, 0)                 AS FC_OH_COST,
    COALESCE(S.OMNI_CATG_NBR, F.OMNI_CATG_NBR) AS OMNI_CATG_NBR,
    COALESCE(S.OMNI_CATG_DESC, F.OMNI_CATG_DESC) AS OMNI_CATG_DESC,
    COALESCE(S.OMNI_DEPT_NBR, F.OMNI_DEPT_NBR)   AS OMNI_DEPT_NBR,
    COALESCE(S.OMNI_DEPT_DESC, F.OMNI_DEPT_DESC)  AS OMNI_DEPT_DESC,
    CASE
      WHEN COALESCE(S.OMNI_DEPT_NBR, F.OMNI_DEPT_NBR) IN (92,95)                      THEN 'PANTRY'
      WHEN COALESCE(S.OMNI_DEPT_NBR, F.OMNI_DEPT_NBR) IN (2,4,8,13,40,46,79)          THEN 'CONSUMABLES'
      WHEN COALESCE(S.OMNI_DEPT_NBR, F.OMNI_DEPT_NBR) IN (3,9,10,11,12,16,19,56)      THEN 'HARDLINES'
      WHEN COALESCE(S.OMNI_DEPT_NBR, F.OMNI_DEPT_NBR) IN (90,91,1,82,96)              THEN 'CAC'
      WHEN COALESCE(S.OMNI_DEPT_NBR, F.OMNI_DEPT_NBR) IN (23,24,25,26,29,31,32,33,34) THEN 'FASHION'
      WHEN COALESCE(S.OMNI_DEPT_NBR, F.OMNI_DEPT_NBR) IN (14,17,20,22,71,74)          THEN 'HOME'
      WHEN COALESCE(S.OMNI_DEPT_NBR, F.OMNI_DEPT_NBR) IN (80,81,93,94,97,98)          THEN 'FRESH'
      WHEN COALESCE(S.OMNI_DEPT_NBR, F.OMNI_DEPT_NBR) IN (5,6,7,18,21,67,72,87)       THEN 'ETS'
      ELSE 'OTHER'
    END AS SBU

  FROM store_channel S
  FULL OUTER JOIN fc_channel F
    ON S.BUS_DT = F.BUS_DT
    AND S.MDS_FAM_ID = F.MDS_FAM_ID
    AND S.OMNI_CATG_NBR = F.OMNI_CATG_NBR

  INNER JOIN `wmt-edw-prod.WW_CORE_DIM_DL_VM.DL_CALENDAR_DIM` CAL
    ON COALESCE(S.BUS_DT, F.BUS_DT) = CAL.CAL_DT

  INNER JOIN ITEM_CUR
    ON COALESCE(S.MDS_FAM_ID, F.MDS_FAM_ID) = ITEM_CUR.MDS_FAM_ID

  LEFT JOIN `wmt-gdap-dl-sec-merch-bq-prod.us_mdse_omni_vm.mdse_omni_item_vw` OMNI
    ON COALESCE(S.MDS_FAM_ID, F.MDS_FAM_ID) = OMNI.MDS_FAM_ID
    AND OMNI.VAL_IND = 1
    AND OMNI.OP_CMPNY_CD = 'WMT-US'
    AND OMNI.MDS_FAM_ID <> -1

  WHERE (
    S.STORE_OH_UNITS > 0
    OR S.DC_RESERVED_UNITS > 0
    OR S.IN_TRANSIT_UNITS > 0
    OR F.FC_OH_UNITS > 0
  )
);


-- ============================================================
-- LEGACY VIEWS (updated to expose ITEM_CUBE)
-- ============================================================

DROP VIEW IF EXISTS `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_STORE_INVT`;
CREATE OR REPLACE VIEW `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_STORE_INVT` AS
SELECT
  BUS_DT, WM_YEAR, WM_WEEK, WM_YR_WK_NBR, MDS_FAM_ID,
  ITEM_CUBE,
  STORE_OH_UNITS, STORE_OH_COST,
  DC_RESERVED_UNITS, DC_RESERVED_COST,
  OMNI_CATG_NBR, OMNI_CATG_DESC, OMNI_DEPT_NBR, OMNI_DEPT_DESC, SBU
FROM `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_STORE_FC_INVT`;

DROP VIEW IF EXISTS `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_TRANSIT_INVT`;
CREATE OR REPLACE VIEW `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_TRANSIT_INVT` AS
SELECT
  BUS_DT, WM_YEAR, WM_WEEK, WM_YR_WK_NBR, MDS_FAM_ID,
  ITEM_CUBE,
  IN_TRANSIT_UNITS, IN_TRANSIT_COST,
  OMNI_CATG_NBR, OMNI_CATG_DESC, OMNI_DEPT_NBR, OMNI_DEPT_DESC, SBU
FROM `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_STORE_FC_INVT`
WHERE IN_TRANSIT_UNITS > 0;

DROP VIEW IF EXISTS `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_FC_INVT`;
CREATE OR REPLACE VIEW `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_FC_INVT` AS
SELECT
  BUS_DT, WM_YEAR, WM_WEEK, WM_YR_WK_NBR, MDS_FAM_ID,
  ITEM_CUBE,
  FC_OH_UNITS, FC_OH_COST,
  OMNI_CATG_NBR, OMNI_CATG_DESC, OMNI_DEPT_NBR, OMNI_DEPT_DESC, SBU
FROM `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_STORE_FC_INVT`
WHERE FC_OH_UNITS > 0;


-- ============================================================
-- STEP 1.5: BACKROOM INVENTORY (daily grain via store_backroom_qty)
-- Single source: RS001_WM_AD_HOC.store_backroom_qty covers full history from WK01 FY25.
-- ============================================================
DROP TABLE IF EXISTS `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_BACKROOM`;

CREATE OR REPLACE TABLE `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_BACKROOM`
PARTITION BY BUS_DT
CLUSTER BY OMNI_CATG_NBR
AS (
  WITH FRIDAY_DATES AS (
    SELECT DISTINCT
      WM_FULL_YR_NBR AS WM_YEAR,
      WM_WK_NBR      AS WM_WEEK,
      WM_YR_WK_NBR,
      CAL_DT         AS BUS_DT
    FROM `wmt-edw-prod.WW_CORE_DIM_DL_VM.DL_CALENDAR_DIM`
    WHERE (
      EXTRACT(DAYOFWEEK FROM CAL_DT) = 6
      OR (CAL_DT = DATE_SUB(CURRENT_DATE('America/Chicago'), INTERVAL 1 DAY)
          AND EXTRACT(DAYOFWEEK FROM CURRENT_DATE('America/Chicago')) BETWEEN 2 AND 6)
    )
      AND CAL_DT >= '2025-02-07'
      AND CAL_DT < CURRENT_DATE('America/Chicago')
  ),

  -- REPL_GRP_NBR → MDS_FAM_ID via pre-filtered ITEM_CUR universe.
  -- 99.8% of REPL_GROUP_NBR values map to a single OMNI category, so
  -- ROW_NUMBER dedup is safe (picks lowest MDS_FAM_ID on rare multi-family keys).
  repl_item_map AS (
    SELECT REPL_GROUP_NBR, MDS_FAM_ID
    FROM ITEM_CUR
    WHERE REPL_GROUP_NBR IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (PARTITION BY REPL_GROUP_NBR ORDER BY MDS_FAM_ID) = 1
  )

  SELECT
    FRI.BUS_DT,
    FRI.WM_YEAR,
    FRI.WM_WEEK,
    FRI.WM_YR_WK_NBR,
    RIM.MDS_FAM_ID,
    SUM(COALESCE(BKRM.TOTAL_BACKROOM_QTY, 0))                                AS BACKROOM_UNITS,
    SAFE_DIVIDE(
      SUM(COALESCE(BKRM.TOTAL_BACKROOM_QTY, 0)
          * SAFE_DIVIDE(OMNI.PKG_HT_IN_QTY * OMNI.PKG_WDTH_IN_QTY * OMNI.PKG_LEN_IN_QTY, 1728)),
      NULLIF(SUM(COALESCE(BKRM.TOTAL_BACKROOM_QTY, 0)), 0)
    )                                                                         AS BACKROOM_WTAVG_CUBE,
    OMNI.OMNI_CATG_NBR,
    OMNI.OMNI_CATG_DESC,
    OMNI.OMNI_DEPT_NBR,
    OMNI.OMNI_DEPT_DESC,
    CASE
      WHEN OMNI.OMNI_DEPT_NBR IN (92,95)                      THEN 'PANTRY'
      WHEN OMNI.OMNI_DEPT_NBR IN (2,4,8,13,40,46,79)          THEN 'CONSUMABLES'
      WHEN OMNI.OMNI_DEPT_NBR IN (3,9,10,11,12,16,19,56)      THEN 'HARDLINES'
      WHEN OMNI.OMNI_DEPT_NBR IN (90,91,1,82,96)              THEN 'CAC'
      WHEN OMNI.OMNI_DEPT_NBR IN (23,24,25,26,29,31,32,33,34) THEN 'FASHION'
      WHEN OMNI.OMNI_DEPT_NBR IN (14,17,20,22,71,74)          THEN 'HOME'
      WHEN OMNI.OMNI_DEPT_NBR IN (80,81,93,94,97,98)          THEN 'FRESH'
      WHEN OMNI.OMNI_DEPT_NBR IN (5,6,7,18,21,67,72,87)       THEN 'ETS'
      ELSE 'OTHER'
    END                                                                       AS SBU
  FROM `wmt-instockinventory-datamart.RS001_WM_AD_HOC.store_backroom_qty` BKRM
  INNER JOIN FRIDAY_DATES FRI
    ON BKRM.CAL_DATE = FRI.BUS_DT
  INNER JOIN repl_item_map RIM
    ON BKRM.REPL_GRP_NBR = RIM.REPL_GROUP_NBR
  LEFT JOIN `wmt-gdap-dl-sec-merch-bq-prod.us_mdse_omni_vm.mdse_omni_item_vw` OMNI
    ON RIM.MDS_FAM_ID = OMNI.MDS_FAM_ID
    AND OMNI.VAL_IND = 1
    AND OMNI.OP_CMPNY_CD = 'WMT-US'
    AND OMNI.MDS_FAM_ID <> -1
  WHERE COALESCE(BKRM.TOTAL_BACKROOM_QTY, 0) > 0
  GROUP BY ALL
);


-- ============================================================
-- STEP 3: DC ON-HAND (with ITEM_CUBE)
-- ============================================================
DROP TABLE IF EXISTS `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_DC_OH`;

CREATE OR REPLACE TABLE `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_DC_OH`
PARTITION BY BUS_DT
CLUSTER BY OMNI_CATG_NBR
AS (
  SELECT
    WDS.INVENTORY_DATE                AS BUS_DT,
    CAL.WM_FULL_YR_NBR                AS WM_YEAR,
    CAL.WM_WK_NBR                     AS WM_WEEK,
    CAL.WM_YR_WK_NBR,
    WDS.ITEM_NBR                      AS MDS_FAM_ID,
    WDS.WHSE_NBR                      AS DC_NBR,
    COALESCE(DC_DIM.DC_TYPE_DESC, 'UNKNOWN') AS DC_TYPE,
    SUM(WDS.ON_HAND_QTY * WDS.WHPK_QTY)      AS DC_OH_UNITS,
    SUM(WDS.ON_HAND_QTY * WDS.WHPK_COST_AMT) AS DC_OH_COST,
    OMNI.OMNI_CATG_NBR,
    OMNI.OMNI_CATG_DESC,
    OMNI.OMNI_DEPT_NBR,
    OMNI.OMNI_DEPT_DESC,
    SAFE_DIVIDE(OMNI.PKG_HT_IN_QTY * OMNI.PKG_WDTH_IN_QTY * OMNI.PKG_LEN_IN_QTY, 1728) AS ITEM_CUBE,
    CASE
      WHEN OMNI.OMNI_DEPT_NBR IN (92,95)                      THEN 'PANTRY'
      WHEN OMNI.OMNI_DEPT_NBR IN (2,4,8,13,40,46,79)          THEN 'CONSUMABLES'
      WHEN OMNI.OMNI_DEPT_NBR IN (3,9,10,11,12,16,19,56)      THEN 'HARDLINES'
      WHEN OMNI.OMNI_DEPT_NBR IN (90,91,1,82,96)              THEN 'CAC'
      WHEN OMNI.OMNI_DEPT_NBR IN (23,24,25,26,29,31,32,33,34) THEN 'FASHION'
      WHEN OMNI.OMNI_DEPT_NBR IN (14,17,20,22,71,74)          THEN 'HOME'
      WHEN OMNI.OMNI_DEPT_NBR IN (80,81,93,94,97,98)          THEN 'FRESH'
      WHEN OMNI.OMNI_DEPT_NBR IN (5,6,7,18,21,67,72,87)       THEN 'ETS'
      ELSE 'OTHER'
    END AS SBU
  FROM `wmt-edw-prod.US_WM_VM.WHSE_DLY_SKU` WDS
  INNER JOIN `wmt-edw-prod.WW_CORE_DIM_DL_VM.DL_CALENDAR_DIM` CAL
    ON WDS.INVENTORY_DATE = CAL.CAL_DT
  LEFT JOIN `wmt-gdap-dl-sec-merch-bq-prod.us_mdse_omni_vm.mdse_omni_item_vw` OMNI
    ON WDS.ITEM_NBR = OMNI.MDS_FAM_ID
    AND OMNI.VAL_IND = 1
    AND OMNI.OP_CMPNY_CD = 'WMT-US'
  INNER JOIN ITEM_CUR
    ON WDS.ITEM_NBR = ITEM_CUR.MDS_FAM_ID
  LEFT JOIN `wmt-edw-prod.WW_CORE_DIM_VM.DC_DIM_CUR` DC_DIM
    ON DC_DIM.COUNTRY_CODE = 'US'
    AND DC_DIM.DC_NBR = WDS.WHSE_NBR
    AND DC_DIM.CURRENT_IND = 'Y'
  WHERE WDS.INVENTORY_DATE >= '2025-02-07'
    AND (
      EXTRACT(DAYOFWEEK FROM WDS.INVENTORY_DATE) = 6
      OR (WDS.INVENTORY_DATE = DATE_SUB(CURRENT_DATE('America/Chicago'), INTERVAL 1 DAY)
          AND EXTRACT(DAYOFWEEK FROM CURRENT_DATE('America/Chicago')) BETWEEN 2 AND 6)
    )
    AND WDS.INVENTORY_DATE < CURRENT_DATE('America/Chicago')
    AND WDS.ON_HAND_QTY > 0
    AND OMNI.OMNI_SEG_DESC NOT IN ('HEALTH AND WELLNESS','OTHER','WALMART SERVICES')
    AND DC_DIM.DC_TYPE_DESC IS NOT NULL
    AND UPPER(DC_DIM.DC_TYPE_DESC) NOT IN ('PHARMACY', 'ADMINISTRATION ACCOUNT')
  GROUP BY ALL
);


-- ============================================================
-- STEP 4: DC LABELED + UNLABELED (with ITEM_CUBE)
-- ============================================================
DROP TABLE IF EXISTS `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_DC_LBL`;

CREATE OR REPLACE TABLE `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_DC_LBL`
PARTITION BY BUS_DT
CLUSTER BY OMNI_CATG_NBR
AS (
  WITH item_unit_cost AS (
    SELECT
      BUS_DT,
      MDS_FAM_ID,
      SAFE_DIVIDE(
        SUM(COALESCE(TY_ON_HAND_COST_AMT, 0)),
        NULLIF(SUM(COALESCE(TY_ON_HAND_QTY, 0)), 0)
      ) AS UNIT_COST
    FROM `wmt-gdap-dl-sec-merch-bq-prod.us_fd_app_secure.fd_omni_chnl_item_dly`
    WHERE BUS_DT >= '2025-02-07'
      AND (
        EXTRACT(DAYOFWEEK FROM BUS_DT) = 6
        OR (BUS_DT = DATE_SUB(CURRENT_DATE('America/Chicago'), INTERVAL 1 DAY)
            AND EXTRACT(DAYOFWEEK FROM CURRENT_DATE('America/Chicago')) BETWEEN 2 AND 6)
      )
      AND BUS_DT < CURRENT_DATE('America/Chicago')
      AND FULFMT_CHNL_NM = 'Store'
      AND TY_ON_HAND_QTY > 0
    GROUP BY BUS_DT, MDS_FAM_ID
  )
  SELECT
    DC.INVENTORY_DATE               AS BUS_DT,
    CAL.WM_FULL_YR_NBR              AS WM_YEAR,
    CAL.WM_WK_NBR                   AS WM_WEEK,
    CAL.WM_YR_WK_NBR,
    DC.ITEM_NBR                     AS MDS_FAM_ID,
    DC.DC_NBR,
    COALESCE(DC_DIM.DC_TYPE_DESC, 'UNKNOWN') AS DC_TYPE,
    DC.INVT_TYPE_CODE,
    SUM(DC.WHPK_INVT_QTY * ITEM.WHPK_QTY)                                   AS DC_LBL_UNLBL_UNITS,
    SUM(DC.WHPK_INVT_QTY * ITEM.WHPK_QTY * COALESCE(UC.UNIT_COST, 0))       AS DC_LBL_UNLBL_COST,
    OMNI.OMNI_CATG_NBR,
    OMNI.OMNI_CATG_DESC,
    OMNI.OMNI_DEPT_NBR,
    OMNI.OMNI_DEPT_DESC,
    SAFE_DIVIDE(OMNI.PKG_HT_IN_QTY * OMNI.PKG_WDTH_IN_QTY * OMNI.PKG_LEN_IN_QTY, 1728) AS ITEM_CUBE,
    CASE
      WHEN OMNI.OMNI_DEPT_NBR IN (92,95)                      THEN 'PANTRY'
      WHEN OMNI.OMNI_DEPT_NBR IN (2,4,8,13,40,46,79)          THEN 'CONSUMABLES'
      WHEN OMNI.OMNI_DEPT_NBR IN (3,9,10,11,12,16,19,56)      THEN 'HARDLINES'
      WHEN OMNI.OMNI_DEPT_NBR IN (90,91,1,82,96)              THEN 'CAC'
      WHEN OMNI.OMNI_DEPT_NBR IN (23,24,25,26,29,31,32,33,34) THEN 'FASHION'
      WHEN OMNI.OMNI_DEPT_NBR IN (14,17,20,22,71,74)          THEN 'HOME'
      WHEN OMNI.OMNI_DEPT_NBR IN (80,81,93,94,97,98)          THEN 'FRESH'
      WHEN OMNI.OMNI_DEPT_NBR IN (5,6,7,18,21,67,72,87)       THEN 'ETS'
      ELSE 'OTHER'
    END AS SBU
  FROM `wmt-edw-prod.US_WM_VM.DC_DLY_INVT_TYPE` DC
  INNER JOIN `wmt-edw-prod.WW_CORE_DIM_DL_VM.DL_CALENDAR_DIM` CAL
    ON DC.INVENTORY_DATE = CAL.CAL_DT
  LEFT JOIN `wmt-edw-prod.US_WM_VM.ITEM_CUR` ITEM
    ON DC.ITEM_NBR = ITEM.MDS_FAM_ID
  LEFT JOIN `wmt-gdap-dl-sec-merch-bq-prod.us_mdse_omni_vm.mdse_omni_item_vw` OMNI
    ON DC.ITEM_NBR = OMNI.MDS_FAM_ID
    AND OMNI.VAL_IND = 1
    AND OMNI.OP_CMPNY_CD = 'WMT-US'
  INNER JOIN ITEM_CUR ITEM_EXCL
    ON DC.ITEM_NBR = ITEM_EXCL.MDS_FAM_ID
  LEFT JOIN `wmt-edw-prod.WW_CORE_DIM_VM.DC_DIM_CUR` DC_DIM
    ON DC_DIM.COUNTRY_CODE = 'US'
    AND DC_DIM.DC_NBR = DC.DC_NBR
    AND DC_DIM.CURRENT_IND = 'Y'
  LEFT JOIN item_unit_cost UC
    ON DC.INVENTORY_DATE = UC.BUS_DT
    AND DC.ITEM_NBR = UC.MDS_FAM_ID
  WHERE DC.INVENTORY_DATE >= '2025-02-07'
    AND (
      EXTRACT(DAYOFWEEK FROM DC.INVENTORY_DATE) = 6
      OR (DC.INVENTORY_DATE = DATE_SUB(CURRENT_DATE('America/Chicago'), INTERVAL 1 DAY)
          AND EXTRACT(DAYOFWEEK FROM CURRENT_DATE('America/Chicago')) BETWEEN 2 AND 6)
    )
    AND DC.INVENTORY_DATE < CURRENT_DATE('America/Chicago')
    AND DC.INVT_TYPE_CODE IN ('L', 'S', 'U')
    AND DC.WHPK_INVT_QTY > 0
    AND OMNI.OMNI_SEG_DESC NOT IN ('HEALTH AND WELLNESS','OTHER','WALMART SERVICES')
    AND DC_DIM.DC_TYPE_DESC IS NOT NULL
    AND UPPER(DC_DIM.DC_TYPE_DESC) NOT IN ('PHARMACY', 'ADMINISTRATION ACCOUNT')
  GROUP BY ALL
);


-- ============================================================
-- STEP 5: STOCK TRANSFER ORDERS (with ITEM_CUBE)
-- ============================================================
DROP TABLE IF EXISTS `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_STO`;

CREATE OR REPLACE TABLE `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_STO`
PARTITION BY BUS_DT
CLUSTER BY OMNI_CATG_NBR
AS (
  WITH item_unit_cost AS (
    SELECT
      BUS_DT,
      MDS_FAM_ID,
      SAFE_DIVIDE(
        SUM(COALESCE(TY_ON_HAND_COST_AMT, 0)),
        NULLIF(SUM(COALESCE(TY_ON_HAND_QTY, 0)), 0)
      ) AS UNIT_COST
    FROM `wmt-gdap-dl-sec-merch-bq-prod.us_fd_app_secure.fd_omni_chnl_item_dly`
    WHERE BUS_DT >= '2025-02-07'
      AND (
        EXTRACT(DAYOFWEEK FROM BUS_DT) = 6
        OR (BUS_DT = DATE_SUB(CURRENT_DATE('America/Chicago'), INTERVAL 1 DAY)
            AND EXTRACT(DAYOFWEEK FROM CURRENT_DATE('America/Chicago')) BETWEEN 2 AND 6)
      )
      AND BUS_DT < CURRENT_DATE('America/Chicago')
      AND FULFMT_CHNL_NM = 'Store'
      AND TY_ON_HAND_QTY > 0
    GROUP BY BUS_DT, MDS_FAM_ID
  ),

  STO_BASE AS (
    SELECT
      DATE(AOF.ALLOC_CREATE_TS)      AS BUS_DT,
      ITEM.ITEM_NBR                   AS MDS_FAM_ID,
      AOF.TO_STORE_NBR                AS DEST_WHSE_NBR,
      AOF.FROM_STORE_NBR              AS SRC_WHSE_NBR,
      SUM(AOF.WHPK_ORD_QTY * AOF.WHPK_QTY) AS STO_UNITS
    FROM `wmt-edw-prod.US_WM_OMS_VM.ALLOC_ORDER_FACT` AOF
    INNER JOIN `wmt-edw-prod.US_WM_OMS_VM.STOCK_TRANSFER_ORDER` STO
      ON AOF.STOCK_TRANSFER_ORD_NBR = STO.STOCK_TRANSFER_ORD_NBR
    INNER JOIN `wmt-edw-prod.US_WM_VM.ITEM` ITEM
      ON ITEM.OLD_NBR = AOF.ITEM_NBR
      AND ITEM.OBSOLETE_DATE IS NULL
    INNER JOIN `wmt-edw-prod.US_WM_OMS_VM.OMS_STO_PO_XREF` STO_XREF
      ON STO_XREF.STOCK_TRANSFER_ORD_NBR = AOF.STOCK_TRANSFER_ORD_NBR
    WHERE DATE(AOF.ALLOC_CREATE_TS) >= '2025-02-07'
      AND (
        EXTRACT(DAYOFWEEK FROM DATE(AOF.ALLOC_CREATE_TS)) = 6
        OR (DATE(AOF.ALLOC_CREATE_TS) = DATE_SUB(CURRENT_DATE('America/Chicago'), INTERVAL 1 DAY)
            AND EXTRACT(DAYOFWEEK FROM CURRENT_DATE('America/Chicago')) BETWEEN 2 AND 6)
      )
      AND DATE(AOF.ALLOC_CREATE_TS) < CURRENT_DATE('America/Chicago')
      AND AOF.WHPK_ORD_QTY > 0
    GROUP BY ALL
  )
  SELECT
    S.BUS_DT,
    CAL.WM_FULL_YR_NBR                AS WM_YEAR,
    CAL.WM_WK_NBR                     AS WM_WEEK,
    CAL.WM_YR_WK_NBR,
    S.MDS_FAM_ID,
    S.DEST_WHSE_NBR                    AS DEST_DC_NBR,
    COALESCE(DEST_DC.DC_TYPE_DESC, 'UNKNOWN') AS DEST_DC_TYPE,
    S.SRC_WHSE_NBR                     AS SRC_DC_NBR,
    COALESCE(SRC_DC.DC_TYPE_DESC, 'UNKNOWN')  AS SRC_DC_TYPE,
    CASE
      WHEN DEST_DC.DC_TYPE_DESC IS NOT NULL AND SRC_DC.DC_TYPE_DESC IS NOT NULL THEN 'DC_TO_DC'
      WHEN DEST_DC.DC_TYPE_DESC IS NULL     AND SRC_DC.DC_TYPE_DESC IS NOT NULL THEN 'DC_TO_STORE'
      WHEN DEST_DC.DC_TYPE_DESC IS NOT NULL AND SRC_DC.DC_TYPE_DESC IS NULL     THEN 'STORE_TO_DC'
      ELSE 'OTHER'
    END AS STO_FLOW_TYPE,
    SUM(S.STO_UNITS)                                         AS STO_UNITS,
    SUM(S.STO_UNITS * COALESCE(UC.UNIT_COST, 0))             AS STO_COST,
    OMNI.OMNI_CATG_NBR,
    OMNI.OMNI_CATG_DESC,
    OMNI.OMNI_DEPT_NBR,
    OMNI.OMNI_DEPT_DESC,
    SAFE_DIVIDE(OMNI.PKG_HT_IN_QTY * OMNI.PKG_WDTH_IN_QTY * OMNI.PKG_LEN_IN_QTY, 1728) AS ITEM_CUBE,
    CASE
      WHEN OMNI.OMNI_DEPT_NBR IN (92,95)                      THEN 'PANTRY'
      WHEN OMNI.OMNI_DEPT_NBR IN (2,4,8,13,40,46,79)          THEN 'CONSUMABLES'
      WHEN OMNI.OMNI_DEPT_NBR IN (3,9,10,11,12,16,19,56)      THEN 'HARDLINES'
      WHEN OMNI.OMNI_DEPT_NBR IN (90,91,1,82,96)              THEN 'CAC'
      WHEN OMNI.OMNI_DEPT_NBR IN (23,24,25,26,29,31,32,33,34) THEN 'FASHION'
      WHEN OMNI.OMNI_DEPT_NBR IN (14,17,20,22,71,74)          THEN 'HOME'
      WHEN OMNI.OMNI_DEPT_NBR IN (80,81,93,94,97,98)          THEN 'FRESH'
      WHEN OMNI.OMNI_DEPT_NBR IN (5,6,7,18,21,67,72,87)       THEN 'ETS'
      ELSE 'OTHER'
    END AS SBU
  FROM STO_BASE S
  INNER JOIN `wmt-edw-prod.WW_CORE_DIM_DL_VM.DL_CALENDAR_DIM` CAL
    ON S.BUS_DT = CAL.CAL_DT
  LEFT JOIN `wmt-edw-prod.WW_CORE_DIM_VM.DC_DIM_CUR` DEST_DC
    ON DEST_DC.COUNTRY_CODE = 'US'
    AND DEST_DC.DC_NBR = S.DEST_WHSE_NBR
    AND DEST_DC.CURRENT_IND = 'Y'
  LEFT JOIN `wmt-edw-prod.WW_CORE_DIM_VM.DC_DIM_CUR` SRC_DC
    ON SRC_DC.COUNTRY_CODE = 'US'
    AND SRC_DC.DC_NBR = S.SRC_WHSE_NBR
    AND SRC_DC.CURRENT_IND = 'Y'
  LEFT JOIN `wmt-gdap-dl-sec-merch-bq-prod.us_mdse_omni_vm.mdse_omni_item_vw` OMNI
    ON S.MDS_FAM_ID = OMNI.MDS_FAM_ID
    AND OMNI.VAL_IND = 1
    AND OMNI.OP_CMPNY_CD = 'WMT-US'
  LEFT JOIN item_unit_cost UC
    ON S.BUS_DT = UC.BUS_DT
    AND S.MDS_FAM_ID = UC.MDS_FAM_ID
  WHERE OMNI.OMNI_SEG_DESC NOT IN ('HEALTH AND WELLNESS','OTHER','WALMART SERVICES')
  GROUP BY ALL
);


-- ============================================================
-- STEP 5.5: ON YARD INVENTORY (with ITEM_CUBE)
-- ============================================================
DROP TABLE IF EXISTS `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_ON_YARD`;

CREATE OR REPLACE TABLE `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_ON_YARD`
PARTITION BY BUS_DT
CLUSTER BY OMNI_CATG_NBR
AS (
  WITH item_unit_cost AS (
    SELECT
      BUS_DT,
      MDS_FAM_ID,
      SAFE_DIVIDE(
        SUM(COALESCE(TY_ON_HAND_COST_AMT, 0)),
        NULLIF(SUM(COALESCE(TY_ON_HAND_QTY, 0)), 0)
      ) AS UNIT_COST
    FROM `wmt-gdap-dl-sec-merch-bq-prod.us_fd_app_secure.fd_omni_chnl_item_dly`
    WHERE BUS_DT >= '2025-02-07'
      AND (
        EXTRACT(DAYOFWEEK FROM BUS_DT) = 6
        OR (BUS_DT = DATE_SUB(CURRENT_DATE('America/Chicago'), INTERVAL 1 DAY)
            AND EXTRACT(DAYOFWEEK FROM CURRENT_DATE('America/Chicago')) BETWEEN 2 AND 6)
      )
      AND BUS_DT < CURRENT_DATE('America/Chicago')
      AND FULFMT_CHNL_NM = 'Store'
      AND TY_ON_HAND_QTY > 0
    GROUP BY BUS_DT, MDS_FAM_ID
  ),

  FRIDAY_DATES AS (
    SELECT DISTINCT
      CAL_DT AS BUS_DT,
      WM_FULL_YR_NBR AS WM_YEAR,
      WM_WK_NBR AS WM_WEEK,
      WM_YR_WK_NBR
    FROM `wmt-edw-prod.WW_CORE_DIM_DL_VM.DL_CALENDAR_DIM`
    WHERE (
      EXTRACT(DAYOFWEEK FROM CAL_DT) = 6
      OR (CAL_DT = DATE_SUB(CURRENT_DATE('America/Chicago'), INTERVAL 1 DAY)
          AND EXTRACT(DAYOFWEEK FROM CURRENT_DATE('America/Chicago')) BETWEEN 2 AND 6)
    )
      AND CAL_DT >= '2025-02-07'
      AND CAL_DT < CURRENT_DATE('America/Chicago')
  ),

  po_first_gate AS (
    SELECT
      PO_NBR,
      WHSE_NBR AS DC_NBR,
      MIN(LEFT(GATE_IN_DATE, 10)) AS first_gate_date
    FROM `wmt-cp-prod.TUP.RDC_FDC_EVENT_POS_HIST`
    WHERE TRAILER_STATUS_CODE IN ('IN', 'XI', 'CI', 'XD')
      AND PO_NBR IS NOT NULL
      AND GATE_IN_DATE IS NOT NULL
    GROUP BY PO_NBR, WHSE_NBR
  ),

  on_yard_base AS (
    SELECT
      pfg.first_gate_date AS GATE_DATE,
      itm.MDS_FAM_ID,
      pfg.DC_NBR,
      SUM(pol.VNPK_ORD_QTY * pol.VNPK_QTY) AS ON_YARD_UNITS
    FROM `wmt-edw-prod.US_WM_OMS_VM.OMS_PURCHASE_ORDER` po
    INNER JOIN `wmt-edw-prod.US_WM_OMS_VM.OMS_PO_LINE` pol
      ON pol.OMS_PO_NBR = po.OMS_PO_NBR
    INNER JOIN (
      SELECT DISTINCT ITEM_NBR, MDS_FAM_ID
      FROM `wmt-edw-prod.US_WM_VM.ITEM_CUR`
      WHERE ITEM_NBR IS NOT NULL AND MDS_FAM_ID IS NOT NULL
      QUALIFY ROW_NUMBER() OVER (PARTITION BY ITEM_NBR ORDER BY OBSOLETE_DATE DESC) = 1
    ) itm ON itm.ITEM_NBR = pol.ITEM_NBR
    INNER JOIN po_first_gate pfg ON pfg.PO_NBR = po.PO_NBR
    WHERE pol.PO_LINE_STATUS_CD <> 1300
      AND po.CHG_REASON_CD <> 49
      AND po.COUNTRY_CODE = 'US'
      AND pfg.first_gate_date >= '2025-02-07'
      AND (
        EXTRACT(DAYOFWEEK FROM DATE(pfg.first_gate_date)) = 6
        OR (DATE(pfg.first_gate_date) = DATE_SUB(CURRENT_DATE('America/Chicago'), INTERVAL 1 DAY)
            AND EXTRACT(DAYOFWEEK FROM CURRENT_DATE('America/Chicago')) BETWEEN 2 AND 6)
      )
      AND DATE(pfg.first_gate_date) < CURRENT_DATE('America/Chicago')
      AND pol.VNPK_ORD_QTY > 0
    GROUP BY pfg.first_gate_date, itm.MDS_FAM_ID, pfg.DC_NBR
  )

  SELECT
    FRI.BUS_DT,
    FRI.WM_YEAR,
    FRI.WM_WEEK,
    FRI.WM_YR_WK_NBR,
    OY.MDS_FAM_ID,
    OY.DC_NBR,
    COALESCE(DC_DIM.DC_TYPE_DESC, 'UNKNOWN') AS DC_TYPE,
    SUM(OY.ON_YARD_UNITS)                                    AS ON_YARD_UNITS,
    SUM(OY.ON_YARD_UNITS * COALESCE(UC.UNIT_COST, 0))        AS ON_YARD_COST,
    OMNI.OMNI_CATG_NBR,
    OMNI.OMNI_CATG_DESC,
    OMNI.OMNI_DEPT_NBR,
    OMNI.OMNI_DEPT_DESC,
    SAFE_DIVIDE(OMNI.PKG_HT_IN_QTY * OMNI.PKG_WDTH_IN_QTY * OMNI.PKG_LEN_IN_QTY, 1728) AS ITEM_CUBE,
    CASE
      WHEN OMNI.OMNI_DEPT_NBR IN (92,95)                      THEN 'PANTRY'
      WHEN OMNI.OMNI_DEPT_NBR IN (2,4,8,13,40,46,79)          THEN 'CONSUMABLES'
      WHEN OMNI.OMNI_DEPT_NBR IN (3,9,10,11,12,16,19,56)      THEN 'HARDLINES'
      WHEN OMNI.OMNI_DEPT_NBR IN (90,91,1,82,96)              THEN 'CAC'
      WHEN OMNI.OMNI_DEPT_NBR IN (23,24,25,26,29,31,32,33,34) THEN 'FASHION'
      WHEN OMNI.OMNI_DEPT_NBR IN (14,17,20,22,71,74)          THEN 'HOME'
      WHEN OMNI.OMNI_DEPT_NBR IN (80,81,93,94,97,98)          THEN 'FRESH'
      WHEN OMNI.OMNI_DEPT_NBR IN (5,6,7,18,21,67,72,87)       THEN 'ETS'
      ELSE 'OTHER'
    END AS SBU
  FROM FRIDAY_DATES FRI
  INNER JOIN on_yard_base OY ON FRI.BUS_DT = DATE(OY.GATE_DATE)
  INNER JOIN ITEM_CUR ON OY.MDS_FAM_ID = ITEM_CUR.MDS_FAM_ID
  LEFT JOIN `wmt-gdap-dl-sec-merch-bq-prod.us_mdse_omni_vm.mdse_omni_item_vw` OMNI
    ON OY.MDS_FAM_ID = OMNI.MDS_FAM_ID
    AND OMNI.VAL_IND = 1
    AND OMNI.OP_CMPNY_CD = 'WMT-US'
  LEFT JOIN `wmt-edw-prod.WW_CORE_DIM_VM.DC_DIM_CUR` DC_DIM
    ON DC_DIM.COUNTRY_CODE = 'US'
    AND DC_DIM.DC_NBR = OY.DC_NBR
    AND DC_DIM.CURRENT_IND = 'Y'
  LEFT JOIN item_unit_cost UC
    ON FRI.BUS_DT = UC.BUS_DT
    AND OY.MDS_FAM_ID = UC.MDS_FAM_ID
  WHERE OMNI.OMNI_SEG_DESC NOT IN ('HEALTH AND WELLNESS','OTHER','WALMART SERVICES')
  GROUP BY ALL
);


-- ============================================================
-- STEP 7: COMBINED INVENTORY TABLE (with AVG_ITEM_CUBE)
-- ============================================================
DROP TABLE IF EXISTS `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_COMBINED`;

CREATE OR REPLACE TABLE `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_COMBINED`
PARTITION BY BUS_DT
CLUSTER BY OMNI_DEPT_NBR, OMNI_CATG_NBR
AS (

  WITH store_fc_agg AS (
    SELECT
      BUS_DT, WM_YEAR, WM_WEEK, WM_YR_WK_NBR,
      OMNI_CATG_NBR, OMNI_CATG_DESC,
      OMNI_DEPT_NBR, OMNI_DEPT_DESC,
      SBU,
      SUM(STORE_OH_UNITS)    AS STORE_OH_UNITS,
      SUM(STORE_OH_COST)     AS STORE_OH_COST,
      SUM(DC_RESERVED_UNITS) AS DC_RESERVED_UNITS,
      SUM(DC_RESERVED_COST)  AS DC_RESERVED_COST,
      SUM(IN_TRANSIT_UNITS)  AS IN_TRANSIT_UNITS,
      SUM(IN_TRANSIT_COST)   AS IN_TRANSIT_COST,
      SUM(FC_OH_UNITS)       AS FC_OH_UNITS,
      SUM(FC_OH_COST)        AS FC_OH_COST,
      SAFE_DIVIDE(SUM(STORE_OH_UNITS    * ITEM_CUBE), NULLIF(SUM(STORE_OH_UNITS), 0))    AS STORE_WTAVG_CUBE,
      SAFE_DIVIDE(SUM(DC_RESERVED_UNITS * ITEM_CUBE), NULLIF(SUM(DC_RESERVED_UNITS), 0)) AS DC_RESERVED_WTAVG_CUBE,
      SAFE_DIVIDE(SUM(IN_TRANSIT_UNITS  * ITEM_CUBE), NULLIF(SUM(IN_TRANSIT_UNITS), 0))  AS TRANSIT_WTAVG_CUBE,
      SAFE_DIVIDE(SUM(FC_OH_UNITS       * ITEM_CUBE), NULLIF(SUM(FC_OH_UNITS), 0))       AS FC_WTAVG_CUBE
    FROM `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_STORE_FC_INVT`
    GROUP BY ALL
  ),

  backroom_agg AS (
    SELECT
      BUS_DT,
      OMNI_CATG_NBR,
      SUM(BACKROOM_UNITS)      AS BACKROOM_UNITS,
      AVG(BACKROOM_WTAVG_CUBE) AS BACKROOM_WTAVG_CUBE
    FROM `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_BACKROOM`
    GROUP BY BUS_DT, OMNI_CATG_NBR
  ),

  dc_oh_agg AS (
    SELECT
      BUS_DT,
      OMNI_CATG_NBR,
      SUM(DC_OH_UNITS)  AS DC_OH_UNITS,
      SUM(DC_OH_COST)   AS DC_OH_COST,
      SAFE_DIVIDE(SUM(DC_OH_UNITS * ITEM_CUBE), NULLIF(SUM(DC_OH_UNITS), 0)) AS DC_OH_WTAVG_CUBE,
      SUM(CASE WHEN DC_TYPE = 'Regional'              THEN DC_OH_UNITS ELSE 0 END) AS DC_OH_REGIONAL_UNITS,
      SUM(CASE WHEN DC_TYPE = 'Grocery'               THEN DC_OH_UNITS ELSE 0 END) AS DC_OH_GROCERY_UNITS,
      SUM(CASE WHEN DC_TYPE = 'Fashion'               THEN DC_OH_UNITS ELSE 0 END) AS DC_OH_FASHION_UNITS,
      SUM(CASE WHEN DC_TYPE = 'Imports'               THEN DC_OH_UNITS ELSE 0 END) AS DC_OH_IMPORTS_UNITS,
      SUM(CASE WHEN DC_TYPE = 'GIDC'                  THEN DC_OH_UNITS ELSE 0 END) AS DC_OH_GIDC_UNITS,
      SUM(CASE WHEN DC_TYPE = 'Market Service Center' THEN DC_OH_UNITS ELSE 0 END) AS DC_OH_MSC_UNITS,
      SUM(CASE WHEN DC_TYPE = 'Support'               THEN DC_OH_UNITS ELSE 0 END) AS DC_OH_SUPPORT_UNITS,
      SUM(CASE WHEN DC_TYPE NOT IN ('Regional','Grocery','Fashion','Imports','GIDC','Market Service Center','Support')
               THEN DC_OH_UNITS ELSE 0 END) AS DC_OH_OTHER_UNITS
    FROM `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_DC_OH`
    GROUP BY BUS_DT, OMNI_CATG_NBR
  ),

  dc_lbl_agg AS (
    SELECT
      BUS_DT,
      OMNI_CATG_NBR,
      SUM(CASE WHEN INVT_TYPE_CODE IN ('L','S') THEN DC_LBL_UNLBL_UNITS ELSE 0 END) AS DC_LABELED_UNITS,
      SUM(CASE WHEN INVT_TYPE_CODE IN ('L','S') THEN DC_LBL_UNLBL_COST  ELSE 0 END) AS DC_LABELED_COST,
      SUM(CASE WHEN INVT_TYPE_CODE = 'U'        THEN DC_LBL_UNLBL_UNITS ELSE 0 END) AS DC_UNLABELED_UNITS,
      SUM(CASE WHEN INVT_TYPE_CODE = 'U'        THEN DC_LBL_UNLBL_COST  ELSE 0 END) AS DC_UNLABELED_COST,
      SAFE_DIVIDE(
        SUM(CASE WHEN INVT_TYPE_CODE IN ('L','S') THEN DC_LBL_UNLBL_UNITS * ITEM_CUBE ELSE 0 END),
        NULLIF(SUM(CASE WHEN INVT_TYPE_CODE IN ('L','S') THEN DC_LBL_UNLBL_UNITS ELSE 0 END), 0)
      ) AS DC_LBL_WTAVG_CUBE,
      SAFE_DIVIDE(
        SUM(CASE WHEN INVT_TYPE_CODE = 'U' THEN DC_LBL_UNLBL_UNITS * ITEM_CUBE ELSE 0 END),
        NULLIF(SUM(CASE WHEN INVT_TYPE_CODE = 'U' THEN DC_LBL_UNLBL_UNITS ELSE 0 END), 0)
      ) AS DC_UNLBL_WTAVG_CUBE
    FROM `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_DC_LBL`
    GROUP BY BUS_DT, OMNI_CATG_NBR
  ),

  sto_agg AS (
    SELECT
      BUS_DT,
      OMNI_CATG_NBR,
      SUM(CASE WHEN STO_FLOW_TYPE IN ('DC_TO_DC','STORE_TO_DC') THEN STO_UNITS ELSE 0 END) AS STO_IN_TRANSIT_TO_DC_UNITS,
      SUM(CASE WHEN STO_FLOW_TYPE IN ('DC_TO_DC','STORE_TO_DC') THEN STO_COST  ELSE 0 END) AS STO_IN_TRANSIT_TO_DC_COST,
      SUM(CASE WHEN STO_FLOW_TYPE IN ('DC_TO_DC','STORE_TO_DC') AND DEST_DC_TYPE = 'Regional'              THEN STO_UNITS ELSE 0 END) AS STO_TO_REGIONAL_UNITS,
      SUM(CASE WHEN STO_FLOW_TYPE IN ('DC_TO_DC','STORE_TO_DC') AND DEST_DC_TYPE = 'Grocery'               THEN STO_UNITS ELSE 0 END) AS STO_TO_GROCERY_UNITS,
      SUM(CASE WHEN STO_FLOW_TYPE IN ('DC_TO_DC','STORE_TO_DC') AND DEST_DC_TYPE = 'Fashion'               THEN STO_UNITS ELSE 0 END) AS STO_TO_FASHION_UNITS,
      SUM(CASE WHEN STO_FLOW_TYPE IN ('DC_TO_DC','STORE_TO_DC') AND DEST_DC_TYPE = 'Imports'               THEN STO_UNITS ELSE 0 END) AS STO_TO_IMPORTS_UNITS,
      SUM(CASE WHEN STO_FLOW_TYPE IN ('DC_TO_DC','STORE_TO_DC') AND DEST_DC_TYPE = 'GIDC'                  THEN STO_UNITS ELSE 0 END) AS STO_TO_GIDC_UNITS,
      SUM(CASE WHEN STO_FLOW_TYPE IN ('DC_TO_DC','STORE_TO_DC') AND DEST_DC_TYPE = 'Market Service Center' THEN STO_UNITS ELSE 0 END) AS STO_TO_MSC_UNITS,
      SUM(CASE WHEN STO_FLOW_TYPE IN ('DC_TO_DC','STORE_TO_DC') AND DEST_DC_TYPE = 'Support'               THEN STO_UNITS ELSE 0 END) AS STO_TO_SUPPORT_UNITS,
      SUM(CASE WHEN STO_FLOW_TYPE IN ('DC_TO_DC','STORE_TO_DC')
               AND DEST_DC_TYPE NOT IN ('Regional','Grocery','Fashion','Imports','GIDC','Market Service Center','Support')
               THEN STO_UNITS ELSE 0 END) AS STO_TO_OTHER_UNITS,
      SAFE_DIVIDE(
        SUM(CASE WHEN STO_FLOW_TYPE IN ('DC_TO_DC','STORE_TO_DC') THEN STO_UNITS * ITEM_CUBE ELSE 0 END),
        NULLIF(SUM(CASE WHEN STO_FLOW_TYPE IN ('DC_TO_DC','STORE_TO_DC') THEN STO_UNITS ELSE 0 END), 0)
      ) AS STO_WTAVG_CUBE
    FROM `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_STO`
    GROUP BY BUS_DT, OMNI_CATG_NBR
  ),

  on_yard_agg AS (
    SELECT
      BUS_DT,
      OMNI_CATG_NBR,
      SUM(ON_YARD_UNITS)  AS ON_YARD_UNITS,
      SUM(ON_YARD_COST)   AS ON_YARD_COST,
      SAFE_DIVIDE(SUM(ON_YARD_UNITS * ITEM_CUBE), NULLIF(SUM(ON_YARD_UNITS), 0)) AS ON_YARD_WTAVG_CUBE,
      SUM(CASE WHEN DC_TYPE = 'Regional'              THEN ON_YARD_UNITS ELSE 0 END) AS ON_YARD_REGIONAL_UNITS,
      SUM(CASE WHEN DC_TYPE = 'Grocery'               THEN ON_YARD_UNITS ELSE 0 END) AS ON_YARD_GROCERY_UNITS,
      SUM(CASE WHEN DC_TYPE = 'Fashion'               THEN ON_YARD_UNITS ELSE 0 END) AS ON_YARD_FASHION_UNITS,
      SUM(CASE WHEN DC_TYPE = 'Imports'               THEN ON_YARD_UNITS ELSE 0 END) AS ON_YARD_IMPORTS_UNITS,
      SUM(CASE WHEN DC_TYPE = 'GIDC'                  THEN ON_YARD_UNITS ELSE 0 END) AS ON_YARD_GIDC_UNITS,
      SUM(CASE WHEN DC_TYPE = 'Market Service Center' THEN ON_YARD_UNITS ELSE 0 END) AS ON_YARD_MSC_UNITS,
      SUM(CASE WHEN DC_TYPE NOT IN ('Regional','Grocery','Fashion','Imports','GIDC','Market Service Center')
               THEN ON_YARD_UNITS ELSE 0 END) AS ON_YARD_OTHER_UNITS
    FROM `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_ON_YARD`
    GROUP BY BUS_DT, OMNI_CATG_NBR
  )

  SELECT
    sfc.BUS_DT,
    sfc.WM_YEAR,
    sfc.WM_WEEK,
    sfc.WM_YR_WK_NBR,
    sfc.OMNI_CATG_NBR,
    sfc.OMNI_CATG_DESC,
    sfc.OMNI_DEPT_NBR,
    sfc.OMNI_DEPT_DESC,
    sfc.SBU,

    sfc.STORE_WTAVG_CUBE,
    b.BACKROOM_WTAVG_CUBE,

    SAFE_DIVIDE(
      sfc.STORE_OH_UNITS    * COALESCE(sfc.STORE_WTAVG_CUBE, 0)
      - COALESCE(b.BACKROOM_UNITS, 0) * COALESCE(b.BACKROOM_WTAVG_CUBE, sfc.STORE_WTAVG_CUBE, 0),
      NULLIF(sfc.STORE_OH_UNITS - COALESCE(b.BACKROOM_UNITS, 0), 0)
    ) AS ON_FLOOR_WTAVG_CUBE,
    sfc.DC_RESERVED_WTAVG_CUBE,
    sfc.TRANSIT_WTAVG_CUBE,
    sfc.FC_WTAVG_CUBE,
    d.DC_OH_WTAVG_CUBE,
    l.DC_LBL_WTAVG_CUBE,
    l.DC_UNLBL_WTAVG_CUBE,
    st.STO_WTAVG_CUBE,
    oy.ON_YARD_WTAVG_CUBE,

    sfc.STORE_OH_UNITS,
    sfc.STORE_OH_COST,
    COALESCE(b.BACKROOM_UNITS, 0)                             AS BACKROOM_UNITS,
    sfc.STORE_OH_UNITS - COALESCE(b.BACKROOM_UNITS, 0)        AS ON_FLOOR_UNITS,
    sfc.DC_RESERVED_UNITS,
    sfc.DC_RESERVED_COST,
    sfc.IN_TRANSIT_UNITS,
    sfc.IN_TRANSIT_COST,
    COALESCE(d.DC_OH_UNITS, 0)         AS DC_OH_UNITS,
    COALESCE(d.DC_OH_COST, 0)          AS DC_OH_COST,
    COALESCE(l.DC_LABELED_UNITS, 0)    AS DC_LABELED_UNITS,
    COALESCE(l.DC_LABELED_COST, 0)     AS DC_LABELED_COST,
    COALESCE(l.DC_UNLABELED_UNITS, 0)  AS DC_UNLABELED_UNITS,
    COALESCE(l.DC_UNLABELED_COST, 0)   AS DC_UNLABELED_COST,
    COALESCE(d.DC_OH_REGIONAL_UNITS, 0) AS DC_OH_REGIONAL_UNITS,
    COALESCE(d.DC_OH_GROCERY_UNITS, 0)  AS DC_OH_GROCERY_UNITS,
    COALESCE(d.DC_OH_FASHION_UNITS, 0)  AS DC_OH_FASHION_UNITS,
    COALESCE(d.DC_OH_IMPORTS_UNITS, 0)  AS DC_OH_IMPORTS_UNITS,
    COALESCE(d.DC_OH_GIDC_UNITS, 0)     AS DC_OH_GIDC_UNITS,
    COALESCE(d.DC_OH_MSC_UNITS, 0)      AS DC_OH_MSC_UNITS,
    COALESCE(d.DC_OH_SUPPORT_UNITS, 0)  AS DC_OH_SUPPORT_UNITS,
    COALESCE(d.DC_OH_OTHER_UNITS, 0)    AS DC_OH_OTHER_UNITS,
    COALESCE(st.STO_IN_TRANSIT_TO_DC_UNITS, 0) AS STO_IN_TRANSIT_TO_DC_UNITS,
    COALESCE(st.STO_IN_TRANSIT_TO_DC_COST, 0)  AS STO_IN_TRANSIT_TO_DC_COST,
    COALESCE(st.STO_TO_REGIONAL_UNITS, 0)       AS STO_TO_REGIONAL_UNITS,
    COALESCE(st.STO_TO_GROCERY_UNITS, 0)        AS STO_TO_GROCERY_UNITS,
    COALESCE(st.STO_TO_FASHION_UNITS, 0)        AS STO_TO_FASHION_UNITS,
    COALESCE(st.STO_TO_IMPORTS_UNITS, 0)        AS STO_TO_IMPORTS_UNITS,
    COALESCE(st.STO_TO_GIDC_UNITS, 0)           AS STO_TO_GIDC_UNITS,
    COALESCE(st.STO_TO_MSC_UNITS, 0)            AS STO_TO_MSC_UNITS,
    COALESCE(st.STO_TO_SUPPORT_UNITS, 0)        AS STO_TO_SUPPORT_UNITS,
    COALESCE(st.STO_TO_OTHER_UNITS, 0)          AS STO_TO_OTHER_UNITS,
    sfc.FC_OH_UNITS,
    sfc.FC_OH_COST,
    COALESCE(oy.ON_YARD_UNITS, 0)          AS ON_YARD_UNITS,
    COALESCE(oy.ON_YARD_COST, 0)           AS ON_YARD_COST,
    COALESCE(oy.ON_YARD_REGIONAL_UNITS, 0) AS ON_YARD_REGIONAL_UNITS,
    COALESCE(oy.ON_YARD_GROCERY_UNITS, 0)  AS ON_YARD_GROCERY_UNITS,
    COALESCE(oy.ON_YARD_FASHION_UNITS, 0)  AS ON_YARD_FASHION_UNITS,
    COALESCE(oy.ON_YARD_IMPORTS_UNITS, 0)  AS ON_YARD_IMPORTS_UNITS,
    COALESCE(oy.ON_YARD_GIDC_UNITS, 0)     AS ON_YARD_GIDC_UNITS,
    COALESCE(oy.ON_YARD_MSC_UNITS, 0)      AS ON_YARD_MSC_UNITS,
    COALESCE(oy.ON_YARD_OTHER_UNITS, 0)    AS ON_YARD_OTHER_UNITS,

    ( sfc.STORE_OH_UNITS
    + sfc.DC_RESERVED_UNITS
    + sfc.IN_TRANSIT_UNITS
    + COALESCE(d.DC_OH_UNITS, 0)
    + COALESCE(l.DC_LABELED_UNITS, 0)
    + COALESCE(l.DC_UNLABELED_UNITS, 0)
    + COALESCE(st.STO_IN_TRANSIT_TO_DC_UNITS, 0)
    + sfc.FC_OH_UNITS
    + COALESCE(oy.ON_YARD_UNITS, 0)
    ) AS TOTAL_NETWORK_UNITS,

    ( sfc.STORE_OH_COST
    + sfc.DC_RESERVED_COST
    + sfc.IN_TRANSIT_COST
    + COALESCE(d.DC_OH_COST, 0)
    + COALESCE(l.DC_LABELED_COST, 0)
    + COALESCE(l.DC_UNLABELED_COST, 0)
    + COALESCE(st.STO_IN_TRANSIT_TO_DC_COST, 0)
    + sfc.FC_OH_COST
    + COALESCE(oy.ON_YARD_COST, 0)
    ) AS TOTAL_NETWORK_COST

  FROM store_fc_agg sfc
  LEFT JOIN backroom_agg b  ON sfc.BUS_DT = b.BUS_DT  AND sfc.OMNI_CATG_NBR = b.OMNI_CATG_NBR
  LEFT JOIN dc_oh_agg d     ON sfc.BUS_DT = d.BUS_DT  AND sfc.OMNI_CATG_NBR = d.OMNI_CATG_NBR
  LEFT JOIN dc_lbl_agg l    ON sfc.BUS_DT = l.BUS_DT  AND sfc.OMNI_CATG_NBR = l.OMNI_CATG_NBR
  LEFT JOIN sto_agg st      ON sfc.BUS_DT = st.BUS_DT AND sfc.OMNI_CATG_NBR = st.OMNI_CATG_NBR
  LEFT JOIN on_yard_agg oy  ON sfc.BUS_DT = oy.BUS_DT AND sfc.OMNI_CATG_NBR = oy.OMNI_CATG_NBR
);


-- ============================================================
-- STEP 8: DC-LEVEL HISTORICAL TABLE (with AVG_ITEM_CUBE)
-- ============================================================
DROP TABLE IF EXISTS `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_DC_LEVEL`;

CREATE OR REPLACE TABLE `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_DC_LEVEL`
PARTITION BY BUS_DT
CLUSTER BY DC_NBR, SBU
AS (

  WITH
  cal AS (
    SELECT DISTINCT
      CAL_DT AS BUS_DT,
      WM_FULL_YR_NBR AS WM_YEAR,
      WM_WK_NBR AS WM_WEEK,
      WM_YR_WK_NBR
    FROM `wmt-edw-prod.WW_CORE_DIM_DL_VM.DL_CALENDAR_DIM`
    WHERE CAL_DT >= '2025-02-07'
      AND (
        EXTRACT(DAYOFWEEK FROM CAL_DT) = 6
        OR (CAL_DT = DATE_SUB(CURRENT_DATE('America/Chicago'), INTERVAL 1 DAY)
            AND EXTRACT(DAYOFWEEK FROM CURRENT_DATE('America/Chicago')) BETWEEN 2 AND 6)
      )
      AND CAL_DT < CURRENT_DATE('America/Chicago')
  ),

  omni_hier AS (
    SELECT DISTINCT
      OMNI_CATG_NBR,
      OMNI_CATG_DESC,
      OMNI_DEPT_NBR,
      OMNI_DEPT_DESC,
      CASE
        WHEN OMNI_DEPT_NBR IN (2,4,8,13,40,46,79)          THEN 'CONSUMABLES'
        WHEN OMNI_DEPT_NBR IN (80,93,94,97,98)             THEN 'FRESH'
        WHEN OMNI_DEPT_NBR IN (90,91,1,82,96)              THEN 'CAC'
        WHEN OMNI_DEPT_NBR IN (81,92,95)                   THEN 'PANTRY'
        WHEN OMNI_DEPT_NBR IN (23,24,25,26,29,31,32,33,34) THEN 'FASHION'
        WHEN OMNI_DEPT_NBR IN (5,6,7,18,21,67,72,87)       THEN 'ETS'
        WHEN OMNI_DEPT_NBR IN (3,9,10,11,12,16,19,56)      THEN 'HARDLINES'
        WHEN OMNI_DEPT_NBR IN (14,17,20,22,71,74)          THEN 'HOME'
        ELSE 'UNASSIGNED'
      END AS SBU
    FROM `wmt-gdap-dl-sec-merch-bq-prod.us_mdse_omni_vm.mdse_omni_item_vw`
    WHERE OMNI_SEG_DESC NOT IN ('HEALTH AND WELLNESS', 'OTHER', 'WALMART SERVICES')
      AND OMNI_CATG_NBR IS NOT NULL
  ),

  dc_oh AS (
    SELECT
      BUS_DT, DC_NBR, DC_TYPE, OMNI_CATG_NBR,
      SUM(DC_OH_UNITS)  AS DC_OH_UNITS,
      SUM(DC_OH_COST)   AS DC_OH_COST,
      SAFE_DIVIDE(SUM(DC_OH_UNITS * ITEM_CUBE), NULLIF(SUM(DC_OH_UNITS), 0)) AS DC_OH_WTAVG_CUBE
    FROM `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_DC_OH`
    WHERE UPPER(DC_TYPE) NOT LIKE '%ECOMM%'
      AND UPPER(DC_TYPE) NOT LIKE '%FULFILLMENT%'
      AND UPPER(DC_TYPE) NOT LIKE '%E-COMMERCE%'
      AND UPPER(DC_TYPE) NOT LIKE 'FC%'
    GROUP BY BUS_DT, DC_NBR, DC_TYPE, OMNI_CATG_NBR
  ),

  dc_lbl AS (
    SELECT
      BUS_DT, DC_NBR, DC_TYPE, OMNI_CATG_NBR,
      SUM(CASE WHEN INVT_TYPE_CODE IN ('L','S') THEN DC_LBL_UNLBL_UNITS ELSE 0 END) AS DC_LABELED_UNITS,
      SUM(CASE WHEN INVT_TYPE_CODE IN ('L','S') THEN DC_LBL_UNLBL_COST  ELSE 0 END) AS DC_LABELED_COST,
      SUM(CASE WHEN INVT_TYPE_CODE = 'U'        THEN DC_LBL_UNLBL_UNITS ELSE 0 END) AS DC_UNLABELED_UNITS,
      SUM(CASE WHEN INVT_TYPE_CODE = 'U'        THEN DC_LBL_UNLBL_COST  ELSE 0 END) AS DC_UNLABELED_COST,
      SAFE_DIVIDE(
        SUM(CASE WHEN INVT_TYPE_CODE IN ('L','S') THEN DC_LBL_UNLBL_UNITS * ITEM_CUBE ELSE 0 END),
        NULLIF(SUM(CASE WHEN INVT_TYPE_CODE IN ('L','S') THEN DC_LBL_UNLBL_UNITS ELSE 0 END), 0)
      ) AS DC_LBL_WTAVG_CUBE,
      SAFE_DIVIDE(
        SUM(CASE WHEN INVT_TYPE_CODE = 'U' THEN DC_LBL_UNLBL_UNITS * ITEM_CUBE ELSE 0 END),
        NULLIF(SUM(CASE WHEN INVT_TYPE_CODE = 'U' THEN DC_LBL_UNLBL_UNITS ELSE 0 END), 0)
      ) AS DC_UNLBL_WTAVG_CUBE
    FROM `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_DC_LBL`
    WHERE UPPER(DC_TYPE) NOT LIKE '%ECOMM%'
      AND UPPER(DC_TYPE) NOT LIKE '%FULFILLMENT%'
      AND UPPER(DC_TYPE) NOT LIKE '%E-COMMERCE%'
      AND UPPER(DC_TYPE) NOT LIKE 'FC%'
    GROUP BY BUS_DT, DC_NBR, DC_TYPE, OMNI_CATG_NBR
  ),

  sto_to_dc AS (
    SELECT
      BUS_DT,
      DEST_DC_NBR    AS DC_NBR,
      DEST_DC_TYPE   AS DC_TYPE,
      OMNI_CATG_NBR,
      SUM(STO_UNITS) AS STO_TO_DC_UNITS,
      SUM(STO_COST)  AS STO_TO_DC_COST,
      SAFE_DIVIDE(SUM(STO_UNITS * ITEM_CUBE), NULLIF(SUM(STO_UNITS), 0)) AS STO_WTAVG_CUBE
    FROM `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_STO`
    WHERE STO_FLOW_TYPE IN ('DC_TO_DC', 'STORE_TO_DC')
      AND UPPER(DEST_DC_TYPE) NOT LIKE '%ECOMM%'
      AND UPPER(DEST_DC_TYPE) NOT LIKE '%FULFILLMENT%'
      AND UPPER(DEST_DC_TYPE) NOT LIKE '%E-COMMERCE%'
      AND UPPER(DEST_DC_TYPE) NOT LIKE 'FC%'
    GROUP BY BUS_DT, DEST_DC_NBR, DEST_DC_TYPE, OMNI_CATG_NBR
  ),

  on_yard AS (
    SELECT
      BUS_DT, DC_NBR, DC_TYPE, OMNI_CATG_NBR,
      SUM(ON_YARD_UNITS) AS ON_YARD_UNITS,
      SUM(ON_YARD_COST)  AS ON_YARD_COST,
      SAFE_DIVIDE(SUM(ON_YARD_UNITS * ITEM_CUBE), NULLIF(SUM(ON_YARD_UNITS), 0)) AS ON_YARD_WTAVG_CUBE
    FROM `wmt-execution-intel-prod.WM_AD_HOC.R0C0JUG_WMUS_HIST_ON_YARD`
    WHERE UPPER(DC_TYPE) NOT LIKE '%ECOMM%'
      AND UPPER(DC_TYPE) NOT LIKE '%FULFILLMENT%'
      AND UPPER(DC_TYPE) NOT LIKE '%E-COMMERCE%'
      AND UPPER(DC_TYPE) NOT LIKE 'FC%'
    GROUP BY BUS_DT, DC_NBR, DC_TYPE, OMNI_CATG_NBR
  ),

  all_dc_keys AS (
    SELECT DISTINCT BUS_DT, DC_NBR, DC_TYPE, OMNI_CATG_NBR FROM dc_oh
    UNION DISTINCT
    SELECT DISTINCT BUS_DT, DC_NBR, DC_TYPE, OMNI_CATG_NBR FROM dc_lbl
    UNION DISTINCT
    SELECT DISTINCT BUS_DT, DC_NBR, DC_TYPE, OMNI_CATG_NBR FROM sto_to_dc
    UNION DISTINCT
    SELECT DISTINCT BUS_DT, DC_NBR, DC_TYPE, OMNI_CATG_NBR FROM on_yard
  )

  SELECT
    k.BUS_DT,
    c.WM_YEAR,
    c.WM_WEEK,
    c.WM_YR_WK_NBR,
    k.DC_NBR,
    k.DC_TYPE,
    h.SBU,
    h.OMNI_DEPT_NBR,
    h.OMNI_DEPT_DESC  AS DEPARTMENT,
    k.OMNI_CATG_NBR,
    h.OMNI_CATG_DESC  AS CATEGORY,
    oh.DC_OH_WTAVG_CUBE,
    lbl.DC_LBL_WTAVG_CUBE,
    lbl.DC_UNLBL_WTAVG_CUBE,
    sto.STO_WTAVG_CUBE,
    oy.ON_YARD_WTAVG_CUBE,
    COALESCE(oh.DC_OH_UNITS, 0)          AS DC_OH_UNITS,
    COALESCE(oh.DC_OH_COST, 0)           AS DC_OH_COST,
    COALESCE(lbl.DC_LABELED_UNITS, 0)    AS DC_LABELED_UNITS,
    COALESCE(lbl.DC_LABELED_COST, 0)     AS DC_LABELED_COST,
    COALESCE(lbl.DC_UNLABELED_UNITS, 0)  AS DC_UNLABELED_UNITS,
    COALESCE(lbl.DC_UNLABELED_COST, 0)   AS DC_UNLABELED_COST,
    COALESCE(sto.STO_TO_DC_UNITS, 0)     AS STO_TO_DC_UNITS,
    COALESCE(sto.STO_TO_DC_COST, 0)      AS STO_TO_DC_COST,
    COALESCE(oy.ON_YARD_UNITS, 0)        AS ON_YARD_UNITS,
    COALESCE(oy.ON_YARD_COST, 0)         AS ON_YARD_COST,

    COALESCE(oh.DC_OH_UNITS, 0)
      + COALESCE(lbl.DC_LABELED_UNITS, 0)
      + COALESCE(lbl.DC_UNLABELED_UNITS, 0)
      + COALESCE(sto.STO_TO_DC_UNITS, 0)
      + COALESCE(oy.ON_YARD_UNITS, 0) AS TOTAL_DC_UNITS,

    COALESCE(oh.DC_OH_COST, 0)
      + COALESCE(lbl.DC_LABELED_COST, 0)
      + COALESCE(lbl.DC_UNLABELED_COST, 0)
      + COALESCE(sto.STO_TO_DC_COST, 0)
      + COALESCE(oy.ON_YARD_COST, 0) AS TOTAL_DC_COST

  FROM all_dc_keys k
  LEFT JOIN cal c       ON c.BUS_DT = k.BUS_DT
  LEFT JOIN omni_hier h ON h.OMNI_CATG_NBR = k.OMNI_CATG_NBR
  LEFT JOIN dc_oh oh
    ON oh.BUS_DT = k.BUS_DT AND oh.DC_NBR = k.DC_NBR AND oh.OMNI_CATG_NBR = k.OMNI_CATG_NBR
  LEFT JOIN dc_lbl lbl
    ON lbl.BUS_DT = k.BUS_DT AND lbl.DC_NBR = k.DC_NBR AND lbl.OMNI_CATG_NBR = k.OMNI_CATG_NBR
  LEFT JOIN sto_to_dc sto
    ON sto.BUS_DT = k.BUS_DT AND sto.DC_NBR = k.DC_NBR AND sto.OMNI_CATG_NBR = k.OMNI_CATG_NBR
  LEFT JOIN on_yard oy
    ON oy.BUS_DT = k.BUS_DT AND oy.DC_NBR = k.DC_NBR AND oy.OMNI_CATG_NBR = k.OMNI_CATG_NBR

  WHERE h.SBU IS NOT NULL
);
